In [1]:
import pandas as pd
import wbgapi as wb
import requests
import openpyxl
import pycountry

In [2]:
#Series Codes of Selected Topics from World Bank - BJV

wb_series_codes = [
"econonmy",
"time",
"NY.GDP.PCAP.KD.ZG",
"NY.GNP.PCAP.KD.ZG",
"SE.XPD.TOTL.GD.ZS",
"SE.ADT.LITR.ZS",
"SE.COM.DURS",
"SE.LPV.PRIM",
"SE.LPV.PRIM.SD",
"SE.SEC.CUAT.LO.ZS",
"SE.SEC.CUAT.PO.ZS",
"SE.SEC.CUAT.UP.ZS",
"SE.TER.CUAT.BA.ZS",
"SE.TER.CUAT.DO.ZS",
"SE.TER.CUAT.MS.ZS",
"SE.TER.CUAT.ST.ZS",
"AG.PRD.FOOD.XD",
"EN.POP.DNST",
"EN.POP.SLUM.UR.ZS",
"SP.RUR.TOTL.ZG",
"EG.ELC.ACCS.ZS",
"ER.H2O.FWST.ZS",
"FX.OWN.TOTL.ZS",
"SN.ITK.MSFI.ZS",
"SH.XPD.CHEX.PC.CD",
"SH.XPD.GHED.PC.CD",
"SH.STA.WASH.P5",
"SP.DYN.LE00.IN",
"SH.UHC.SRVS.CV.XD",
"IT.NET.BBND.P2",
"IT.NET.USER.ZS",
"GB.XPD.RSDV.GD.ZS",
"IS.SHP.GCNW.XQ",
"SI.POV.GINI",
"VC.IHR.PSRC.P5",
"CC.EST",
"GE.EST",
"PV.EST",
"RL.EST",
"VA.EST",
"SM.POP.TOTL.ZS"
]


print("Collecting information provided by World Bank Series Codes:\n")

Collecting information provided by World Bank Series Codes:

In [3]:
#create a data frame from the World Bank API  - BJV
wb_df = wb.data.DataFrame(
        wb_series_codes,
        economy='all',
        time=range(1995,2024),
        columns='series'
    )


print("Data retrieval complete: Displaying first 5 rows:")
print(wb_df.head())

print("\nDataFrame Info:")
wb_df.info()

print(f"\nDataFrame shape: {wb_df.shape} (rows, columns)")

Data retrieval complete: Displaying first 5 rows:
                AG.PRD.FOOD.XD  CC.EST  EG.ELC.ACCS.ZS  EN.POP.DNST  \
economy time
ABW     YR1995             NaN     NaN           100.0   443.361111
        YR1996             NaN     NaN           100.0   461.227778
        YR1997             NaN     NaN           100.0   479.450000
        YR1998             NaN     NaN           100.0   491.394444
        YR1999             NaN     NaN           100.0   498.105556

                EN.POP.SLUM.UR.ZS  ER.H2O.FWST.ZS  FX.OWN.TOTL.ZS  \
economy time
ABW     YR1995                NaN             NaN             NaN
        YR1996                NaN             NaN             NaN
        YR1997                NaN             NaN             NaN
        YR1998                NaN             NaN             NaN
        YR1999                NaN             NaN             NaN

                GB.XPD.RSDV.GD.ZS  GE.EST  IS.SHP.GCNW.XQ  ...  \
economy time                                               ...
ABW     YR1995                NaN     NaN             NaN  ...
        YR1996                NaN     NaN             NaN  ...
        YR1997                NaN     NaN             NaN  ...
        YR1998                NaN     NaN             NaN  ...
        YR1999                NaN     NaN             NaN  ...

                SH.UHC.SRVS.CV.XD  SH.XPD.CHEX.PC.CD  SH.XPD.GHED.PC.CD  \
economy time
ABW     YR1995                NaN                NaN                NaN
        YR1996                NaN                NaN                NaN
        YR1997                NaN                NaN                NaN
        YR1998                NaN                NaN                NaN
        YR1999                NaN                NaN                NaN

                SI.POV.GINI  SM.POP.TOTL.ZS  SN.ITK.MSFI.ZS  SP.DYN.LE00.IN  \
economy time
ABW     YR1995          NaN       27.729502             NaN          72.832
        YR1996          NaN             NaN             NaN          72.856
        YR1997          NaN             NaN             NaN          72.904
        YR1998          NaN             NaN             NaN          72.940
        YR1999          NaN             NaN             NaN          72.857

                SP.RUR.TOTL.ZG  VA.EST  VC.IHR.PSRC.P5
economy time
ABW     YR1995        3.610860     NaN        7.787151
        YR1996        4.750120     NaN             NaN
        YR1997        4.666101     NaN             NaN
        YR1998        3.245730     NaN             NaN
        YR1999        2.132050     NaN        2.302370

[5 rows x 39 columns]

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7714 entries, ('ABW', 'YR1995') to ('ZWE', 'YR2023')
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AG.PRD.FOOD.XD     6642 non-null   float64
 1   CC.EST             4988 non-null   float64
 2   EG.ELC.ACCS.ZS     7195 non-null   float64
 3   EN.POP.DNST        7272 non-null   float64
 4   EN.POP.SLUM.UR.ZS  2435 non-null   float64
 5   ER.H2O.FWST.ZS     4496 non-null   float64
 6   FX.OWN.TOTL.ZS     653 non-null    float64
 7   GB.XPD.RSDV.GD.ZS  3062 non-null   float64
 8   GE.EST             4964 non-null   float64
 9   IS.SHP.GCNW.XQ     2628 non-null   float64
 10  IT.NET.BBND.P2     5104 non-null   float64
 11  IT.NET.USER.ZS     5671 non-null   float64
 12  NY.GDP.PCAP.KD.ZG  7337 non-null   float64
 13  NY.GNP.PCAP.KD.ZG  4628 non-null   float64
 14  PV.EST             5025 non-null   float64
 15  RL.EST             5078 non-null   float64
 16  SE.ADT.LITR.ZS     2060 non-null   float64
 17  SE.COM.DURS        6027 non-null   float64
 18  SE.LPV.PRIM        364 non-null    float64
 19  SE.LPV.PRIM.SD     364 non-null    float64
 20  SE.SEC.CUAT.LO.ZS  1926 non-null   float64
 21  SE.SEC.CUAT.PO.ZS  1406 non-null   float64
 22  SE.SEC.CUAT.UP.ZS  1996 non-null   float64
 23  SE.TER.CUAT.BA.ZS  1314 non-null   float64
 24  SE.TER.CUAT.DO.ZS  1150 non-null   float64
 25  SE.TER.CUAT.MS.ZS  1124 non-null   float64
 26  SE.TER.CUAT.ST.ZS  1712 non-null   float64
 27  SE.XPD.TOTL.GD.ZS  4861 non-null   float64
 28  SH.STA.WASH.P5     231 non-null    float64
 29  SH.UHC.SRVS.CV.XD  1428 non-null   float64
 30  SH.XPD.CHEX.PC.CD  5461 non-null   float64
 31  SH.XPD.GHED.PC.CD  5448 non-null   float64
 32  SI.POV.GINI        2006 non-null   float64
 33  SM.POP.TOTL.ZS     1300 non-null   float64
 34  SN.ITK.MSFI.ZS     1021 non-null   float64
 35  SP.DYN.LE00.IN     7685 non-null   float64
 36  SP.RUR.TOTL.ZG     7345 non-null   float64
 37  VA.EST             5051 non-null   float64
 38  VC.IHR.PSRC.P5     3735 non-null   float64
dtypes: float64(39)
memory usage: 2.3+ MB

DataFrame shape: (7714, 39) (rows, columns)

In [4]:
# Index needs to be reset in ordert for 'economy' and 'time' to be accessed and renamed - BJV
wb_df = wb_df.reset_index()

wb_df = wb_df.rename(columns={'economy': 'ISO3', 'time': 'year'})

# Remove 'YR" from the 'year' column to leave just four digit years - BJV
wb_df['year'] = wb_df['year'].astype(str).str.replace('YR', '', regex=False)
    
# convert the year to a numeric from string for errors arising later - BJV
wb_df['year'] = pd.to_numeric(wb_df['year'], errors='coerce').astype('Int64')


print("\nDataFrame Info:")
wb_df.info()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7714 entries, 0 to 7713
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ISO3               7714 non-null   object
 1   year               7714 non-null   Int64
 2   AG.PRD.FOOD.XD     6642 non-null   float64
 3   CC.EST             4988 non-null   float64
 4   EG.ELC.ACCS.ZS     7195 non-null   float64
 5   EN.POP.DNST        7272 non-null   float64
 6   EN.POP.SLUM.UR.ZS  2435 non-null   float64
 7   ER.H2O.FWST.ZS     4496 non-null   float64
 8   FX.OWN.TOTL.ZS     653 non-null    float64
 9   GB.XPD.RSDV.GD.ZS  3062 non-null   float64
 10  GE.EST             4964 non-null   float64
 11  IS.SHP.GCNW.XQ     2628 non-null   float64
 12  IT.NET.BBND.P2     5104 non-null   float64
 13  IT.NET.USER.ZS     5671 non-null   float64
 14  NY.GDP.PCAP.KD.ZG  7337 non-null   float64
 15  NY.GNP.PCAP.KD.ZG  4628 non-null   float64
 16  PV.EST             5025 non-null   float64
 17  RL.EST             5078 non-null   float64
 18  SE.ADT.LITR.ZS     2060 non-null   float64
 19  SE.COM.DURS        6027 non-null   float64
 20  SE.LPV.PRIM        364 non-null    float64
 21  SE.LPV.PRIM.SD     364 non-null    float64
 22  SE.SEC.CUAT.LO.ZS  1926 non-null   float64
 23  SE.SEC.CUAT.PO.ZS  1406 non-null   float64
 24  SE.SEC.CUAT.UP.ZS  1996 non-null   float64
 25  SE.TER.CUAT.BA.ZS  1314 non-null   float64
 26  SE.TER.CUAT.DO.ZS  1150 non-null   float64
 27  SE.TER.CUAT.MS.ZS  1124 non-null   float64
 28  SE.TER.CUAT.ST.ZS  1712 non-null   float64
 29  SE.XPD.TOTL.GD.ZS  4861 non-null   float64
 30  SH.STA.WASH.P5     231 non-null    float64
 31  SH.UHC.SRVS.CV.XD  1428 non-null   float64
 32  SH.XPD.CHEX.PC.CD  5461 non-null   float64
 33  SH.XPD.GHED.PC.CD  5448 non-null   float64
 34  SI.POV.GINI        2006 non-null   float64
 35  SM.POP.TOTL.ZS     1300 non-null   float64
 36  SN.ITK.MSFI.ZS     1021 non-null   float64
 37  SP.DYN.LE00.IN     7685 non-null   float64
 38  SP.RUR.TOTL.ZG     7345 non-null   float64
 39  VA.EST             5051 non-null   float64
 40  VC.IHR.PSRC.P5     3735 non-null   float64
dtypes: Int64(1), float64(39), object(1)
memory usage: 2.4+ MB

In [5]:
#save this data frame as an xlsx - BJV
wb_df.to_excel("wb_api_dataframe_full3.xlsx", index=True)

In [6]:
# The API call would throw an error if I tried to do more than 
#two years at a time, so individual df were made and concat to resolve this -BJV

In [7]:
# UNDP API Key and Request - BJV

undp_url = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2022,2023"

response = requests.get(undp_url)

if response.status_code == 200:
    data = response.json()

df1 = pd.DataFrame(data)

In [8]:
# UNDP API Key and Request - BJV

undp_url2 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2020,2021"

response2 = requests.get(undp_url2)

if response2.status_code == 200:
    data2 = response2.json()

df2 = pd.DataFrame(data2)

In [9]:
# UNDP API Key and Request - BJV

undp_url3 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2018,2019"

response3 = requests.get(undp_url3)

if response3.status_code == 200:
    data3 = response3.json()

df3 = pd.DataFrame(data3)

In [10]:
# UNDP API Key and Request - BJV

undp_url4 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2016,2017"

response4 = requests.get(undp_url4)

if response4.status_code == 200:
    data4 = response4.json()

df4 = pd.DataFrame(data4)

In [11]:
# UNDP API Key and Request - BJV

undp_url5 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2014,2015"

response5 = requests.get(undp_url5)

if response5.status_code == 200:
    data5 = response5.json()

df5 = pd.DataFrame(data5)

In [12]:
# UNDP API Key and Request - BJV

undp_url6 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2012,2013"

response6 = requests.get(undp_url6)

if response6.status_code == 200:
    data6 = response6.json()

df6 = pd.DataFrame(data6)

In [13]:
# UNDP API Key and Request - BJV

undp_url7 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2010,2011"

response7 = requests.get(undp_url7)

if response7.status_code == 200:
    data7 = response7.json()

df7 = pd.DataFrame(data7)

In [14]:
# UNDP API Key and Request - BJV

undp_url8 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2008,2009"

response8 = requests.get(undp_url8)

if response8.status_code == 200:
    data8 = response8.json()

df8 = pd.DataFrame(data8)

In [15]:
# UNDP API Key and Request - BJV

undp_url9 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2006,2007"

response9 = requests.get(undp_url9)

if response9.status_code == 200:
    data9 = response9.json()

df9 = pd.DataFrame(data9)

In [16]:
# UNDP API Key and Request - BJV

undp_url10 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2004,2005"

response10 = requests.get(undp_url10)

if response10.status_code == 200:
    data10 = response10.json()

df10 = pd.DataFrame(data10)

In [17]:
# UNDP API Key and Request - BJV

undp_url11 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2002,2003"

response11 = requests.get(undp_url11)

if response11.status_code == 200:
    data11 = response11.json()

df11 = pd.DataFrame(data11)

In [18]:
# UNDP API Key and Request - BJV

undp_url12 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=2000,2001"

response12 = requests.get(undp_url12)

if response12.status_code == 200:
    data12 = response12.json()

df12 = pd.DataFrame(data12)

In [19]:
# UNDP API Key and Request - BJV

undp_url13 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=1998,1999"

response13 = requests.get(undp_url13)

if response13.status_code == 200:
    data13 = response13.json()

df13 = pd.DataFrame(data13)

In [20]:
# UNDP API Key and Request - BJV

undp_url14 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=1996,1997"

response14 = requests.get(undp_url14)

if response14.status_code == 200:
    data14 = response14.json()

df14 = pd.DataFrame(data14)

In [21]:
# UNDP API Key and Request - BJV

undp_url15 = "https://hdrdata.org/api/CompositeIndices/query?apikey=HDR-KOgLmhxaLjacLvGRi4oTPARBLx54ubNe&year=1995"

response15 = requests.get(undp_url15)

if response15.status_code == 200:
    data15 = response15.json()

df15 = pd.DataFrame(data15)

In [22]:
all_dataframes = [df1, df2, df3, df4, df5, df6, df7, df8,
                 df9, df10, df11, df12, df13, df14, df15]

In [23]:
# Create a list of all data frames to be concatenated. -BJV
list_of_dfs = [df1, df2, df3, df4, df5, df6, df7, df8,
               df9, df10, df11, df12, df13, df14, df15]

# Concatenate all the data frames in the list. - BJV

combined_df = pd.concat(list_of_dfs, ignore_index=True)

# You can now work with the single combined DataFrame. -BJV
print(combined_df.head())
print(f"The final combined data has {len(combined_df)} rows.")

             country           dimension  \
0  AFG - Afghanistan
1  AFG - Afghanistan
2  AFG - Afghanistan  Standard of Living
3  AFG - Afghanistan              Health
4  AFG - Afghanistan

                                               index  \
0                      GII - Gender Inequality Index
1                      GII - Gender Inequality Index
2               MPI - Multidimensional Poverty Index
3               MPI - Multidimensional Poverty Index
4  PHDI - Planetary pressures–adjusted Human Deve...

                                           indicator  year   value
0  abr - Adolescent Birth Rate (births per 1,000 ...  2022  65.339
1  abr - Adolescent Birth Rate (births per 1,000 ...  2023  64.068
2                                assets - Assets (%)  2022   5.934
3              child_mortality - Child mortality (%)  2022   3.628
4  co2_prod - Carbon dioxide emissions per capita...  2022   0.257
The final combined data has 178619 rows.

In [24]:
# Create a df from a dictionary for saving file - BJV
undp_full_df = pd.DataFrame(combined_df)

In [25]:
# Country needed to split the ISO3 and the Country names - BJV
split_data = undp_full_df['country'].str.split(' - ', n=1, expand=True)

undp_full_df['ISO3 Code'] = split_data[0]
undp_full_df['Country Name'] = split_data[1]

# Drop the original 'Country' column - BJV
undp_full_df_split = undp_full_df.drop(columns=['country'])

In [26]:
# 'Value' was causing and error and needed to be converted to numeric - BJV
undp_full_df_split['value'] = pd.to_numeric(undp_full_df_split['value'], errors='coerce')    

# Data needed to be pivoted for clarity when doing EDA - BJV

undp_full_df_pivoted = undp_full_df_split.pivot_table(index=['ISO3 Code', 'year'], 
                            columns='indicator', 
                            values='value')

undp_full_df_pivoted = undp_full_df_pivoted.rename(columns={'ISO3 Code': 'ISO3'})

print(undp_full_df_pivoted.columns)

Index(['abr - Adolescent Birth Rate (births per 1,000 women ages 15-19)',
       'assets - Assets (%)', 'child_mortality - Child mortality (%)',
       'co2_prod - Carbon dioxide emissions per capita (production) (tonnes)',
       'coef_ineq - Coefficient of human inequality',
       'cooking_fuel - Cooking fuel (%)',
       'diff_hdi_phdi - Difference from HDI value (%)',
       'drinking_water - Drinking water (%)', 'electricity - Electricity (%)',
       'eys - Expected Years of Schooling (years)',
       'eys_f - Expected Years of Schooling, female (years)',
       'eys_m - Expected Years of Schooling, male (years)',
       'gdi - Gender Development Index (value)', 'gdi_group - GDI Group',
       'gii - Gender Inequality Index (value)', 'gii_rank - GII Rank',
       'gni_pc_f - Gross National Income Per Capita, female (2021 PPP$)',
       'gni_pc_m - Gross National Income Per Capita, male (2021 PPP$)',
       'gnipc - Gross National Income Per Capita (2021 PPP$)',
       'hdi - Human Development Index (value)', 'hdi_f - HDI female',
       'hdi_m - HDI male', 'hdi_rank - HDI Rank', 'housing - Housing (%)',
       'ihdi - Inequality-adjusted Human Development Index (value)',
       'ineq_edu - Inequality in eduation', 'ineq_inc - Inequality in income',
       'ineq_le - Inequality in life expectancy',
       'le - Life Expectancy at Birth (years)',
       'le_f - Life Expectancy at Birth, female (years)',
       'le_m - Life Expectancy at Birth, male (years)',
       'lfpr_f - Labour force participation rate, female (% ages 15 and older)',
       'lfpr_m - Labour force participation rate, male (% ages 15 and older)',
       'loss - Overall loss (%)',
       'mf - Material footprint per capita (tonnes)',
       'mmr - Maternal Mortality Ratio (deaths per 100,000 live births)',
       'mpi_value - MPI Value (Range: 0 to 1)',
       'mys - Mean Years of Schooling (years)',
       'mys_f - Mean Years of Schooling, female (years)',
       'mys_m - Mean Years of Schooling, male (years)',
       'nutrition - Nutrition (%)',
       'phdi - Planetary pressures–adjusted Human Development Index (value)',
       'pop_total - Population, total (millions)',
       'pr_f - Share of seats in parliament, female (% held by women)',
       'pr_m - Share of seats in parliament, male (% held by men)',
       'rankdiff_hdi_phdi - Difference from HDI rank',
       'sanitation - Sanitation (%)',
       'school_attendance - School attendance (%)',
       'se_f - Population with at least some secondary education, female (% ages 25 and older)',
       'se_m - Population with at least some secondary education, male (% ages 25 and older)',
       'years_of_schooling - Years of schooling (%)'],
      dtype='object', name='indicator')

In [27]:
# These are the columns that are relevant to our study from the total column options - BJV

columns_to_keep = [
    'hdi - Human Development Index (value)',
    'gii_rank - GII Rank',
    'rankdiff_hdi_phdi - Difference from HDI rank',
    'ihdi - Inequality-adjusted Human Development Index (value)',
    'coef_ineq - Coefficient of human inequality',
    'ineq_le - Inequality in life expectancy',
    'le - Life Expectancy at Birth (years)',
    'ineq_edu - Inequality in eduation',
    'ineq_inc - Inequality in income',
    'coef_ineq - Coefficient of human inequality'
]

undp_full_df_pivoted.index.rename(
    ['ISO3', 'year'], 
    inplace=True
)

undp_df_filtered = undp_full_df_pivoted[columns_to_keep]

undp_df_filtered = undp_df_filtered.reset_index()

In [28]:
print("Data retrieval complete: Displaying first 5 rows:")
print(undp_df_filtered.head())

print("\nDataFrame Info:")
undp_df_filtered.info()

print(f"\nDataFrame shape: {undp_df_filtered.shape} (rows, columns)")

Data retrieval complete: Displaying first 5 rows:
indicator ISO3  year  hdi - Human Development Index (value)  \
0          AFG  1995                                  0.329
1          AFG  1996                                  0.334
2          AFG  1997                                  0.338
3          AFG  1998                                  0.338
4          AFG  1999                                  0.347

indicator  gii_rank - GII Rank  rankdiff_hdi_phdi - Difference from HDI rank  \
0                          NaN                                           NaN
1                          NaN                                           NaN
2                          NaN                                           NaN
3                          NaN                                           NaN
4                          NaN                                           NaN

indicator  ihdi - Inequality-adjusted Human Development Index (value)  \
0                                                        NaN
1                                                        NaN
2                                                        NaN
3                                                        NaN
4                                                        NaN

indicator  coef_ineq - Coefficient of human inequality  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN

indicator  ineq_le - Inequality in life expectancy  \
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN

indicator  le - Life Expectancy at Birth (years)  \
0                                         52.103
1                                         52.830
2                                         53.212
3                                         52.487
4                                         54.532

indicator  ineq_edu - Inequality in eduation  ineq_inc - Inequality in income  \
0                                        NaN                              NaN
1                                        NaN                              NaN
2                                        NaN                              NaN
3                                        NaN                              NaN
4                                        NaN                              NaN

indicator  coef_ineq - Coefficient of human inequality
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5974 entries, 0 to 5973
Data columns (total 12 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   ISO3                                                        5974 non-null   object
 1   year                                                        5974 non-null   object
 2   hdi - Human Development Index (value)                       5552 non-null   float64
 3   gii_rank - GII Rank                                         172 non-null    float64
 4   rankdiff_hdi_phdi - Difference from HDI rank                156 non-null    float64
 5   ihdi - Inequality-adjusted Human Development Index (value)  2297 non-null   float64
 6   coef_ineq - Coefficient of human inequality                 2304 non-null   float64
 7   ineq_le - Inequality in life expectancy                     2884 non-null   float64
 8   le - Life Expectancy at Birth (years)                       5974 non-null   float64
 9   ineq_edu - Inequality in eduation                           2543 non-null   float64
 10  ineq_inc - Inequality in income                             2489 non-null   float64
 11  coef_ineq - Coefficient of human inequality                 2304 non-null   float64
dtypes: float64(10), object(2)
memory usage: 560.2+ KB

DataFrame shape: (5974, 12) (rows, columns)

In [29]:
undp_df_filtered['year'] = pd.to_numeric(undp_df_filtered['year'], errors='coerce').astype('Int64')

In [30]:
# Joined Work Bank and UNDP Data Frames - BJV

undp_wb_filtered_full = pd.merge(undp_df_filtered, wb_df, on=['ISO3', 'year'], how='left')

In [31]:
# Use pycountry to map country names to IS03 codes -BJV
iso3_to_name_map = {}
for country in pycountry.countries:
    iso3_to_name_map[country.alpha_3] = country.name

mapped_full_df = pd.DataFrame(undp_wb_filtered_full)

# Add the 'Country Name' column - BJV
mapped_full_df['Country Name'] = mapped_full_df['ISO3'].map(iso3_to_name_map)

In [32]:
cols = mapped_full_df.columns.tolist()
print(cols)

['ISO3', 'year', 'hdi - Human Development Index (value)', 'gii_rank - GII Rank', 'rankdiff_hdi_phdi - Difference from HDI rank', 'ihdi - Inequality-adjusted Human Development Index (value)', 'coef_ineq - Coefficient of human inequality', 'ineq_le - Inequality in life expectancy', 'le - Life Expectancy at Birth (years)', 'ineq_edu - Inequality in eduation', 'ineq_inc - Inequality in income', 'coef_ineq - Coefficient of human inequality', 'AG.PRD.FOOD.XD', 'CC.EST', 'EG.ELC.ACCS.ZS', 'EN.POP.DNST', 'EN.POP.SLUM.UR.ZS', 'ER.H2O.FWST.ZS', 'FX.OWN.TOTL.ZS', 'GB.XPD.RSDV.GD.ZS', 'GE.EST', 'IS.SHP.GCNW.XQ', 'IT.NET.BBND.P2', 'IT.NET.USER.ZS', 'NY.GDP.PCAP.KD.ZG', 'NY.GNP.PCAP.KD.ZG', 'PV.EST', 'RL.EST', 'SE.ADT.LITR.ZS', 'SE.COM.DURS', 'SE.LPV.PRIM', 'SE.LPV.PRIM.SD', 'SE.SEC.CUAT.LO.ZS', 'SE.SEC.CUAT.PO.ZS', 'SE.SEC.CUAT.UP.ZS', 'SE.TER.CUAT.BA.ZS', 'SE.TER.CUAT.DO.ZS', 'SE.TER.CUAT.MS.ZS', 'SE.TER.CUAT.ST.ZS', 'SE.XPD.TOTL.GD.ZS', 'SH.STA.WASH.P5', 'SH.UHC.SRVS.CV.XD', 'SH.XPD.CHEX.PC.CD', 'SH.XPD.GHED.PC.CD', 'SI.POV.GINI', 'SM.POP.TOTL.ZS', 'SN.ITK.MSFI.ZS', 'SP.DYN.LE00.IN', 'SP.RUR.TOTL.ZG', 'VA.EST', 'VC.IHR.PSRC.P5', 'Country Name']

In [33]:
current_index_of_country_name = cols.index('Country Name')

# Pop country name - BJV

column_to_move = cols.pop(current_index_of_country_name)

# Move 'country name' to column 2 
cols.insert(1, column_to_move)

mapped_full_df = mapped_full_df[cols]

In [34]:
#save this data frame as an xlsx - BJV
mapped_full_df.to_excel("undp_wb_mappedfiltered_full2.xlsx", index=True)